spring.application.name=gilgaltour
spring.datasource.url=jdbc:mysql://localhost:3306/gilgaltourbasedatos
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
